#!/bin/bash
#
# Startup script for TagTracker on Linux
#
# This will navigate to TagTracker folder, run TagTracker,
# then (on user confirmation), run it again.  (This because
# program may well have shut down to reset for next day.)

TT_DIR="$HOME/TagTracker"

this_dir="$(pwd)"
this_prog=$0
prog_name="${0##*/}"

echo "Starting TagTracker..."
echo

cd "$TT_DIR" || exit 1
python3 tagtracker.py
echo
echo "TagTracker done."
echo
read -rp "Restart TagTracker? (Y/N): " confirm
echo
if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
  exec "$this_prog"
fi
# Do not restart
cd "$this_dir" || exit 1
echo "To restart TagTracker, enter \"$prog_name\""
echo
