#!/bin/bash
#
# Startup script for TagTracker on Linux
#
# This will navigate to TagTracker folder, run TagTracker,
# then (on user confirmation), run it again.  (This because
# program may well have shut down to reset for next day.)

echo "This 'startup' command has been replaced by the 'tagtracker' command."
echo
echo "To start Tagtracker, enter the command 'tagtracker'"
exit 1

